In [40]:
import numpy as np
import pandas as pd

In [41]:
df=pd.read_csv(r"C:\inetpub\Downloads\Mobile Devices\credit_risk_dataset.csv")

In [42]:
df.head()

,Age,Income,Loan_Amount,Credit_Score,Employment_Years,Education_Level,Housing_Status,Default
0,59,52154.0,11276,823,15,Bachelors,Own,0
1,49,116646.0,43663,315,5,PhD,Own,0
2,35,61157.0,18994,428,8,Masters,Own,1
3,63,52154.0,28499,408,26,Bachelors,Rent,0
4,28,148876.0,28040,832,3,Masters,Own,1

In [43]:
df.shape

(1000, 8)

In [44]:
df.isnull().sum()

Age                  0
Income              15
Loan_Amount          0
Credit_Score         0
Employment_Years     0
Education_Level      0
Housing_Status       0
Default              0
dtype: int64

In [45]:
df_num_clm=df.select_dtypes(include=['int', 'float'])

In [46]:
df_cat_clm = df.select_dtypes(include=['object', 'string'])

# Num cols

In [47]:
df_num_clm.isnull().sum()

Age                  0
Income              15
Loan_Amount          0
Credit_Score         0
Employment_Years     0
Default              0
dtype: int64

In [48]:
df_num_clm['Income'] = df_num_clm['Income'].fillna(df_num_clm['Income'].median())

In [49]:
df_num_clm.isnull().sum()

Age                 0
Income              0
Loan_Amount         0
Credit_Score        0
Employment_Years    0
Default             0
dtype: int64

# Cat cols

In [50]:
df_cat_clm.isnull().sum()

Education_Level    0
Housing_Status     0
dtype: int64

In [51]:
cat_col=df_cat_clm.columns

In [52]:
cat_col

Index(['Education_Level', 'Housing_Status'], dtype='str')

In [53]:
from sklearn.preprocessing import OneHotEncoder

In [54]:
ohe=OneHotEncoder(sparse_output=False)

In [55]:
for i in cat_col:
    df_cat_clm=pd.get_dummies(df_cat_clm,columns=[i],drop_first=True,dtype=int)

In [56]:
df_cat_clm.shape

(1000, 5)

# Concat both cat and num cols

In [57]:
df2=pd.concat([df_cat_clm,df_num_clm], axis=1)

In [58]:
df2.head()

,Education_Level_High School,Education_Level_Masters,Education_Level_PhD,Housing_Status_Own,Housing_Status_Rent,Age,Income,Loan_Amount,Credit_Score,Employment_Years,Default
0,0,0,0,1,0,59,52154.0,11276,823,15,0
1,0,0,1,1,0,49,116646.0,43663,315,5,0
2,0,1,0,1,0,35,61157.0,18994,428,8,1
3,0,0,0,0,1,63,52154.0,28499,408,26,0
4,0,1,0,1,0,28,148876.0,28040,832,3,1

In [59]:
from sklearn.model_selection import train_test_split

In [60]:
X = df2.drop("Default", axis=1)
y = df2["Default"]
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=12)

In [61]:
from sklearn.preprocessing import StandardScaler

ss = StandardScaler()

arr = ss.fit_transform(X)

df3_scale = pd.DataFrame(arr, columns=X.columns)

# Logistic Regression

In [62]:
from sklearn.linear_model import LogisticRegression

In [63]:
lr=LogisticRegression(class_weight='balanced')

In [64]:
lr.fit(X_train,y_train)

C:\Users\ujjwa\PycharmProjects\JupyterProject\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(class_weight='balanced')

In [65]:
y_pred=lr.predict(X_test)

In [66]:
lr.score(X_test,y_pred)

1.0

In [67]:
from sklearn.metrics import precision_score, recall_score,f1_score, confusion_matrix, classification_report

In [68]:
print('P_score', precision_score(y_test, y_pred))

P_score 0.14814814814814814

In [69]:
print('R_score', recall_score(y_test, y_pred))

R_score 0.41379310344827586

In [70]:
print('f1_score', f1_score(y_test, y_pred))

f1_score 0.21818181818181817

In [71]:
print(confusion_matrix(y_test, y_pred))

[[102  69]
 [ 17  12]]

In [72]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.86      0.60      0.70       171
           1       0.15      0.41      0.22        29

    accuracy                           0.57       200
   macro avg       0.50      0.51      0.46       200
weighted avg       0.75      0.57      0.63       200